POST http://localhost:5000/books
Content-Type: application/json;charset=utf-8

{
    "author": "New Author",
    "book_name": "New Book Name",
    "book_number": "004",
    "book_price": 45.0,
    "book_publisher": "New Publisher",
    "book_type": "New Type"
}

###

GET http://localhost:5000/books
Accept: application/json;charset=utf-8

###

PUT http://localhost:5000/books/3
Content-Type: application/json;charset=utf-8

{
    "author": "Updated Author",
    "book_name": "Updated Book Name",
    "book_number": "003",
    "book_price": 99.9,
    "book_publisher": "Updated Publisher",
    "book_type": "Updated Type"
}
### 

DELETE http://localhost:5000/books/3
Accept: application/json
